### ISSUE TITLE
Not triggering as expected can't see why

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/time-resource#15]
```
resources:
- name: nightly
  type: time
  source:
    start: 00:01 AM
    stop: 02:00 AM
```
Stopped triggering a couple of days ago, can't see why... How to debug?

![screen shot 2017-03-07 at 10 26 52](https://cloud.githubusercontent.com/assets/2795016/23649941/93b43fbc-0320-11e7-9c84-fe7e55e99a35.png)
