### ISSUE TITLE
scheduled trigger behavior is not intuitive

### ISSUE THREAD

**Issue by craigbookwalter** [concourse/time-resource#16]
Hi, 
Given a resource:
```
    name: timer
    type: time
    source:
      days:
      - Monday
      start: 7:00 AM
      stop: 7:30 AM
```

If a resource like this has already triggered today, it will not trigger again, even if the interval itself is modified in the pipeline definition. If I modify the interval of the resource it should reset and prepare to run again in the new interval.

**Comment by jtarchie** [comment]
@craigbookwalter, can you clarify with examples what the change interval you are referring to.

**Comment by craigbookwalter** [comment]
I'm speaking primarily about when developing a new pipeline. When iterating on a pipeline, I am often re-setting the time resource for intervals a few minutes into the future, for quick iterations. But for a time resource named "X", it will only trigger once. Changes to X's interval do not seem to matter if X has already triggered once. So in order to iterate on a new pipeline and change the interval as I develop, I need to rename X throughout my whole pipeline to set a new interval.

I think that changing the interval of this resource should nix any previous triggers and render the resource ready to trigger again.

example: it's monday morning, 10:10 AM EST, and I have a new pipeline that triggers on a set time that I want to test. I set the `timer` resource for 10:15AM like so:

```
    name: timer
    type: time
    source:
      days:
      - Monday
      start: 10:15 AM
      stop: 10:20 AM
```
It triggers, my pipeline runs. I see something I need to fix, so I check in a fix and now I want to do another run triggered by the timer. It's now 10:30, so I change the interval to trigger soon:

```
    name: timer
    type: time
    source:
      days:
      - Monday
      start: 10:30 AM
      stop: 10:35 AM
```
But my pipeline never triggers, because the `timer` resource has already triggered, and my interval change was not sufficient to clear the resource's memory of having triggered earlier. Instead I have to do a global search/replace to rename the resource.
