### ISSUE TITLE
Add ability for builds to only run within a particular time window.

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/time-resource#17]
In concourse/concourse#945, @krishicks requested that we add the ability for builds to run exclusively during a particular time window. The following is quoted from his original feature request:
 
---

@mariash came up with a solution that does this

```
resources:
- name: after-midnight
  type: time
  source:
    interval: 30s
    start: 12:00 AM
    stop: 1:00 AM
    location: America/Bahia_Banderas
    
jobs:
- name: after-midnight-banana-check
  plan:
  - get: banana
  - get: after-midnight
    trigger: true
  
- name: banana-unit
   plan:
  - get: banana
    trigger: true
    passed: [after-midnight-banana-check]
  - task: run-unit
```

The banana-unit job will only run during the after-midnight time window, which is good. But it's not optimal, because as she notes, it's like using a job as a check, and that's gross. Additionally, it doesn't solve the first problem, of wanting to only run jobs when they have a unique set of resources available.
