### ISSUE TITLE
time-resource is not working properly

### ISSUE THREAD

**Issue by kkitai** [concourse/time-resource#19]
Hi.

I'm using concourse bosh release [3.3.1](http://bosh.io/releases/github.com/concourse/concourse?version=3.3.1) and applied `default_check_interval` property to bosh in order to change the default 1m check interval.
```
  jobs:
  - name: atc
    release: concourse
    properties:
      ...
      default_check_interval: 12h
```

When I set pipeline using time-resource like a following, I expect to be run my-task by 1m. But actually it looks like to be trigged by 12h.
```
resources:
- name: every-1m
  type: time
  check_every: 1m
  source:
    interval: 1m
    location: Asia/Tokyo

jobs:
- name: my-job
  plan:
  - get: every-1m
    trigger: true
  - task: my-task
    config:
```

![Imgur](http://i.imgur.com/989kqx0.png)
