### ISSUE TITLE
jobs not starting with a manual trigger

### ISSUE THREAD

**Issue by jtarchie** [concourse/time-resource#2]
We've been able to recreate an issue, where a job with a fresh time resource and it is manually triggered, will stall (gray state). It looks like the job is waiting for the `check` state of the time resource to past its first version.

We are able to recreate it with this pipeline, as a long as it before 7PM EST, which is the time resource *start time*.

```
resources:
  - name: time-resource
    type: time
    source:
      interval: 12h
      start: 19:00 -0400
      stop: 00:00 -0400

jobs:
  - name: test
    plan:
      - get: time-resource
        trigger: true
      - task: hello world
        config:
          platform: linux
          image: docker:///ubuntu
          run:
            path: echo
            args: ['Hello World']
```
