### ISSUE TITLE
If two time resources are specified, job will not trigger until both resources are satisfied. 

### ISSUE THREAD

**Issue by DonBower** [concourse/time-resource#20]
I have a pipeline, to backup Ops Manager, which I want to run twice a day.
But when I first start the pipeline, and it's just after noon in Chicago, the job does not start.
It seems there has to be both resources are triggered.
```
- name: trigger-daily-after-12am
  type: time
  source:
    start: 00:00
    stop: 03:00
    location: America/Chicago

- name: trigger-daily-after-12pm
  type: time
  source:
    start: 12:00
    stop: 15:00
    location: America/Chicago
```
And the jobs section has:
```
  - get: trigger-daily-after-12am
    trigger: true

  - get: trigger-daily-after-12pm
    trigger: true
```
