### ISSUE TITLE
interval does not trigger

### ISSUE THREAD

**Issue by razvan-moj** [concourse/time-resource#28]
The pipeline below runs only once, while I'd expect it to execute every 5 mins:
```
resources:
- name: 5m
  type: time
  source:
    interval: 5m
- name: app-source
  type: git
  source:
    uri: https://github.com/test-repo
    branch: test-branch
    git_crypt_key: ((ref-secret.ref-key))
jobs:
- name: check-secrets-every-5m
  plan:
  - get: app-source
  - get: 5m
    trigger: true
  - task: check-stuff
    config:
      platform: linux
      inputs:
        - name: app-source
      image_resource:
        type: docker-image
        source:
          repository: repo/concourse-workers
          tag: worker-demo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            echo "hello world"
```
The pipeline is definitely not paused, and the task always succeeds when triggered manually, just not every 5 mins
