### ISSUE TITLE
Question: Refactoring Existing Pipeline To Use Time Resource

### ISSUE THREAD

**Issue by akamalov** [concourse/time-resource#32]
Greetings,

I am trying to refactor current pipeline time resource, but not too sure I understand documentation correctly. This is a snippet from ```bbr-pipeline```, which I am trying to run every Tuesday at 11:30PM EST:

```
resources:

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webhook))
- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.git
    branch: master
- name: om-backup-artifact
  type: s3
  source:
    bucket: ((backup-artifact-bucket))
    region_name: ((storage-region))
    endpoint: ((storage-endpoint))
    access_key_id: ((storage-access-key-id))
    secret_access_key: ((storage-secret-access-key))
    versioned_file: installation.zip
    use_v2_signing: ((storage-use-v2-signing))
    disable_ssl: ((disable_ssl))
- name: ert-backup-bucket
  type: s3
  source:
    bucket: ((backup-artifact-bucket))
    region_name: ((storage-region))
    endpoint: ((storage-endpoint))
    access_key_id: ((storage-access-key-id))
    secret_access_key: ((storage-secret-access-key))
    versioned_file: ert-backup.tar
    use_v2_signing: ((storage-use-v2-signing))
    disable_ssl: ((disable_ssl))
- name: director-backup-bucket
  type: s3
  source:
    bucket: ((backup-artifact-bucket))
    region_name: ((storage-region))
    endpoint: ((storage-endpoint))
    access_key_id: ((storage-access-key-id))
    secret_access_key: ((storage-secret-access-key))
    versioned_file: director-backup.tar
    use_v2_signing: ((storage-use-v2-signing))
    disable_ssl: ((disable_ssl))

```

Now,  do I nest ```type: time``` on each : (?)

```
type: time
  source:
     location: America/New_York
     days: [Tuesday]
     start: 2330
```

How do I go about doing it  ?

Thanks so much in advance.
