### ISSUE TITLE
Using Time Resource, many repeats...

### ISSUE THREAD

**Issue by akamalov** [concourse/time-resource#33]
Wondering if anyone can help. I am using time-resource in conjunction with BBR pipelines https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.  So far, a job kicks off at scheduled time, however, it keeps on repeating over and over.

Snippet:

```
- name: ert-backup-bucket
  type: s3
  tags:
  - ((concourse-worker-tag))
  source:
    bucket: ((backup-artifact-bucket))
    region_name: ((storage-region))
    endpoint: ((storage-endpoint))
    access_key_id: ((storage-access-key-id))
    secret_access_key: ((storage-secret-access-key))
    versioned_file: ert-backup.tar
    use_v2_signing: ((storage-use-v2-signing))
    disable_ssl: ((disable_ssl))

- name: director-backup-bucket
  tags:
  - ((concourse-worker-tag))
  type: s3
  source:
    bucket: ((backup-artifact-bucket))
    region_name: ((storage-region))
    endpoint: ((storage-endpoint))
    access_key_id: ((storage-access-key-id))
    secret_access_key: ((storage-secret-access-key))
    versioned_file: director-backup.tar
    use_v2_signing: ((storage-use-v2-signing))
    disable_ssl: ((disable_ssl))

- name: run-schedule
  type: time
  tags:
  - ((concourse-worker-tag))
  source:
     location: America/New_York
     days: [Saturday]
     start: 1:00 AM
     stop: 3:00 AM

```

![image](https://user-images.githubusercontent.com/7885257/46307258-6c695f00-c584-11e8-9021-b818164367bc.png)

Is there any way I can specify to run once ?

Thanks so much!!
