### ISSUE TITLE
Doc: Document how check works

### ISSUE THREAD

**Issue by kallisti5** [concourse/time-resource#42]
I'd like to trigger at a time *only* if there are updates to a branch. (nightly images, only build if git repo has changes)

I *think* check could be used for that? However not really sure how it works since there is no documentation or examples of it in this repo.

```
  - name: master-time-trigger
    type: time
    source:
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
  - name: r1beta1-time-trigger
    type: time
    source:
      days: [Sunday]
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
  - name: r1beta2-time-trigger
    type: time
    source:
      days: [Monday,Friday]
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago

.
.
     - get: ((branch))-time-trigger
        trigger: true
      - get: haiku-git
        trigger: false
      - task: build ((branch)) anyboot
```
