### ISSUE TITLE
Make time resource versions more predictable

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/time-resource#45]
## What challenge are you facing?

Right now time resource versions are unpredictable. The resource `check` will output the current timestamp after its `interval` has elapsed (or whatever other configuration is used). However, if the `check` gets delayed then the gap between versions is unpredictable.

## What would make this better?

Make time resource versions more predictable. Instead of emitting the current timestamp, emit versions at set times based on the interval specified. This means that if the last version emitted was `1:42:05` and the interval was `1m` then if the check runs at say `1:45:30` the following versions would be emitted: `1:43:05`, `1:44:05`, `1:45:05`. This way regardless of when the check actually runs, we end up with a deterministic set of versions.

**Comment by owenfarrell** [comment]
So, I started hacking away at this yesterday, but came across some key questions. Below are the assumptions that I've started running with.

**A1:  When provided with a previous version, `check` should a list of all valid versions since the specified version**

The assumption here is to strictly adhere to the [contract](https://concourse-ci.org/implementing-resource-types.html#resource-check) for implementing a resource and that anyone who wants to trigger jobs for every version can configure the pipeline to do just that.

Example:
```
resources:
- name: this_resource_should_generate_3_new_versions_each_time_it_is_checked
  type: time
  check_every: 15m
  source:
    interval: 5m
```

**A2:  When defining an `interval` and a `start`, new versions will be generated based on the start time (not the previous version)**

The assumption here is to essentially "reset" the interval calculation each day. This ensures consistency for situations where the specified interval doesn't divide evenly in to a 24 hour period or where there aren't 24 hours in a day (switching to/from daylight saving time).

Example:
```
resources:
- name: this_interval_does_not_divide_evenly_in_to_24h
  type: time
  source:
    interval: 35m
    start: 3:00am
    stop: 6:00am
```

The above configuration would generate the following versions every day (note that these are the versions generated, not _**when**_ the versions are generated).

* 3:00:00
* 3:35:00
* 4:05:00
* 4:40:00
* 5:15:00
* 5:50:00

**A3: Implementing this kind of consistency only applies when an `interval` is defined.**

If an `interval` is not defined, then the existing behavior (generating a version based on the current timestamp) will continue when within the `start`/`stop` window.
