### ISSUE TITLE
every-1m time does not run every 1 minute

### ISSUE THREAD

**Issue by michaelpporter** [concourse/time-resource#75]
### Describe the bug

We have a few jobs that should run every minute, we have noticed that it does not always run in that window.

```yaml
- name: every-1m
  type: time
  icon: clock-outline
  source:
    interval: 1m
```

As you can see by the screenshot, this one has waited over 5 min, it was over 6 before it ran.

![Image](https://github.com/user-attachments/assets/067d580e-c4eb-4ed0-9f2a-61aed7d266c1)

Is this caused by not having workers ready or not enough resources on web?

### Reproduction steps

1. A time resource with a interval: 1m
2. 
3.
...

### Expected behavior

Expected to run every 60 seconds ± 20 seconds

### Additional context

We have 5 web servers 

```yaml
      cpu: "4"
      memory: "12Gi"
```

And 8 workers for this team

```yaml
      cpu: "8"
      memory: "24Gi"
```

**Comment by taylorsilva** [comment]
This happens because Concourse has a default "check interval". That interval determines how often a check will be performed for all resources in your cluster.

The default value is 1min, but it appears your operator has set it to a higher value. You can override this in your pipeline by setting `check_every` (https://concourse-ci.org/resources.html#schema.resource.check_every) to 1min or even 30s. I wouldn't go lower than 30s as it'll likely have no effect on the check frequency (more intervals!).

**Comment by michaelpporter** [comment]
@taylorsilva I am not seeing a global setting for the `check_every`, we do have some get repos that are set to every 2h. 

I have updated our 1-minute tasks; it has helped in some cases, but not all. I will keep checking it out, maybe we need to add `check_every` to all time resources.

```yaml
  - name: every-1m
    type: time
    icon: clock-outline
    source:
      interval: 1m
    check_every: 1m
```
