### ISSUE TITLE
time resource triggers more often than expected

### ISSUE THREAD

**Issue by craigfurman** [concourse/time-resource#8]
We configured a nightly build, using the following resource config (we are using concourse 1.1.0):

```yaml
- name: every-night
  type: time
  source:
    start: 10:00 PM +0000
    stop: 11:00 PM +0000
    days:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
```

It triggered at 2016-06-14T22:00:05.180887057Z (expected), but also 2016-06-14T23:00:08.543509788Z (not expected). We were trying to follow the [trigger-exactly-once](https://github.com/concourse/time-resource#trigger-once-within-time-range) example in the readme.

Is the resource not behaving as expected, or is there another way to get a build to trigger exactly once within a range?
